CREATE SCHEMA IF NOT EXISTS leadbot;

CREATE TABLE IF NOT EXISTS leadbot.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id BIGINT NOT NULL UNIQUE,
    username TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS leadbot.categories (
    id INTEGER PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    full_title TEXT NOT NULL,
    emoji TEXT NOT NULL,
    monthly_leads INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS leadbot.user_category_state (
    user_id BIGINT NOT NULL,
    category_id INTEGER NOT NULL,
    free_leads_total INTEGER NOT NULL,
    free_leads_used INTEGER NOT NULL DEFAULT 0,
    free_started BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (user_id, category_id),
    FOREIGN KEY (user_id) REFERENCES leadbot.users(id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES leadbot.categories(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS leadbot.subscriptions (
    user_id BIGINT NOT NULL,
    category_id INTEGER NOT NULL,
    status TEXT NOT NULL,
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    grant_type TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    auto_renew BOOLEAN NOT NULL DEFAULT FALSE,
    provider TEXT,
    payment_method_id TEXT,
    last_payment_id TEXT,
    canceled_at TEXT,
    PRIMARY KEY (user_id, category_id),
    FOREIGN KEY (user_id) REFERENCES leadbot.users(id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES leadbot.categories(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS leadbot.leads (
    lead_id BIGINT PRIMARY KEY,
    category_id INTEGER NOT NULL,
    text TEXT NOT NULL,
    contact TEXT,
    source TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (category_id) REFERENCES leadbot.categories(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS leadbot.sent_leads (
    user_id BIGINT NOT NULL,
    category_id INTEGER NOT NULL,
    lead_id BIGINT NOT NULL,
    sent_at TEXT NOT NULL,
    PRIMARY KEY (user_id, lead_id),
    FOREIGN KEY (user_id) REFERENCES leadbot.users(id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES leadbot.categories(id) ON DELETE CASCADE,
    FOREIGN KEY (lead_id) REFERENCES leadbot.leads(lead_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS leadbot.category_state (
    category_id INTEGER PRIMARY KEY,
    last_lead_id BIGINT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (category_id) REFERENCES leadbot.categories(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS leadbot.pending_leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category_id INTEGER NOT NULL,
    lead_id BIGINT NOT NULL,
    created_at TEXT NOT NULL,
    UNIQUE (user_id, category_id, lead_id),
    FOREIGN KEY (user_id) REFERENCES leadbot.users(id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES leadbot.categories(id) ON DELETE CASCADE,
    FOREIGN KEY (lead_id) REFERENCES leadbot.leads(lead_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS leadbot.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category_id INTEGER NOT NULL,
    provider TEXT NOT NULL,
    payment_id TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL,
    amount_rub INTEGER NOT NULL,
    currency TEXT NOT NULL,
    confirmation_url TEXT,
    idempotence_key TEXT,
    kind TEXT NOT NULL,
    lead_id BIGINT,
    payment_method_id TEXT,
    cancellation_reason TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    paid_at TEXT,
    applied_at TEXT,
    lead_delivered_at TEXT,
    FOREIGN KEY (user_id) REFERENCES leadbot.users(id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES leadbot.categories(id) ON DELETE CASCADE,
    FOREIGN KEY (lead_id) REFERENCES leadbot.leads(lead_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS leadbot.supabase_state (
    id INTEGER PRIMARY KEY,
    last_message_time TEXT,
    last_message_id BIGINT
);

CREATE INDEX IF NOT EXISTS idx_leadbot_leads_category_id_lead_id
    ON leadbot.leads(category_id, lead_id);

CREATE INDEX IF NOT EXISTS idx_leadbot_sent_leads_user_category
    ON leadbot.sent_leads(user_id, category_id, lead_id);

CREATE INDEX IF NOT EXISTS idx_leadbot_user_category_state_category
    ON leadbot.user_category_state(category_id);

CREATE INDEX IF NOT EXISTS idx_leadbot_pending_leads_user_category
    ON leadbot.pending_leads(user_id, category_id, id);

CREATE INDEX IF NOT EXISTS idx_leadbot_payments_user_category_status
    ON leadbot.payments(user_id, category_id, status);

CREATE INDEX IF NOT EXISTS idx_leadbot_payments_status_created
    ON leadbot.payments(status, created_at);

GRANT USAGE ON SCHEMA leadbot TO contractor_leads_reader;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA leadbot TO contractor_leads_reader;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA leadbot TO contractor_leads_reader;

ALTER DEFAULT PRIVILEGES IN SCHEMA leadbot
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO contractor_leads_reader;

ALTER DEFAULT PRIVILEGES IN SCHEMA leadbot
    GRANT USAGE, SELECT ON SEQUENCES TO contractor_leads_reader;

GRANT SELECT ON TABLE public.system_config TO contractor_leads_reader;

INSERT INTO public.system_config (key, value, updated_by, updated_at)
VALUES ('leadbot_enabled', to_jsonb(TRUE), 'system', NOW())
ON CONFLICT (key) DO NOTHING;
